"""CitationValidatorService (spec item 8). The `citations` returned to
the client are already trustworthy by construction — they're built
directly from `matched_chunks`/`prepared.chunks` (see domain/citations.py),
never generated by the LLM. What ISN'T guaranteed by construction is the
inline `[p. X]` markers the model writes *inside the answer text itself*
(prompts.py's system prompt instructs it to add these) — the model could
in principle cite a page it wasn't actually given, or misremember one
from earlier in the conversation. This service catches that: it's a
hallucination check on the answer's own citation markers, not on the
structured `citations` list.
"""

import re
from dataclasses import dataclass

from ..domain.citations import physical_page_citation_value
from ..domain.entities import DocumentChunk

# Matches "[p. X]" where X is whatever physical_page_citation_value produces —
# always a plain physical page number (str(chunk.physical_page)) since
# this project removed the page_label/display_page concept; the pattern
# stays permissive (anything up to the closing bracket) only so a
# multi-page citation like "[p. 10-12]" or "[p. 10] [p. 11]" still
# parses, not because a non-numeric label is expected anymore.
_INLINE_CITATION_RE = re.compile(r"\[p\.\s*([^\]]+)\]", re.IGNORECASE)


@dataclass
class CitationValidationResult:
    valid_labels: list[str]
    invalid_labels: list[str]  # cited in the answer but not present in the context it was given
    total_citations: int

    @property
    def all_valid(self) -> bool:
        return not self.invalid_labels

    @property
    def confidence_penalty(self) -> float:
        """0.0 (no penalty) when every inline citation checks out, up to
        0.5 when every single one is invalid — used as one input to the
        final response's confidence_score (see answer_generator_service.py)."""
        if self.total_citations == 0:
            return 0.0
        return 0.5 * (len(self.invalid_labels) / self.total_citations)


class CitationValidatorService:
    def validate(self, answer_text: str, context_chunks: list[DocumentChunk]) -> CitationValidationResult:
        """`context_chunks` must be exactly what the model was given
        (prepared.chunks, post context-management) — validating against
        anything narrower or wider would produce false positives/negatives."""
        available_labels = {physical_page_citation_value(c).strip().lower() for c in context_chunks}

        cited = [m.strip() for m in _INLINE_CITATION_RE.findall(answer_text)]
        valid = [c for c in cited if c.lower() in available_labels]
        invalid = [c for c in cited if c.lower() not in available_labels]

        return CitationValidationResult(valid_labels=valid, invalid_labels=invalid, total_citations=len(cited))
