"""Domain interfaces ("ports" in hexagonal-architecture terms). The
application layer depends only on these Protocols — never on a concrete
OpenAI/PyMuPDF/SQLAlchemy class directly. This is what makes "swap OpenAI
for a local embedding model" or "swap SQLite brute-force for pgvector" a
matter of writing one new adapter class that satisfies the same Protocol,
rather than touching business logic.

Python's `Protocol` gives structural typing — a class doesn't need to
explicitly inherit from these to satisfy them, it just needs the matching
methods. Kept as Protocols (not ABCs) deliberately, so infrastructure
classes stay simple and don't need to import this module just to comply.
"""

from typing import Protocol

from .entities import DocumentChunk, ScoredChunk


class EmbeddingService(Protocol):
    def embed_batch(self, texts: list[str]) -> list[list[float]]: ...
    def embed_one(self, text: str) -> list[float]: ...


class LLMService(Protocol):
    def complete(self, messages: list[dict], temperature: float = 0) -> str: ...
    def complete_vision(self, prompt: str, image_png_bytes: bytes) -> str: ...


class DocumentParser(Protocol):
    def extract_chunks(self, pdf_bytes: bytes, chat_id: int, chunk_size: int = 800) -> list[DocumentChunk]: ...


class OCRService(Protocol):
    """Separate from DocumentParser deliberately — Phase 1 flagged that
    OCR currently jumps straight to a vision-model call with no local-OCR
    tier and no retry/backoff. Isolating it behind its own interface now
    means that cascade (embedded text → local OCR → vision fallback) can
    be built inside this one adapter later without the parser needing to
    change at all."""

    def transcribe_page_image(self, image_png_bytes: bytes) -> str: ...


class VectorStore(Protocol):
    def top_k_with_scores(
        self, chunks: list[DocumentChunk], query_embedding: list[float], k: int = 4
    ) -> list[ScoredChunk]: ...


class ChatRepository(Protocol):
    def get_owned_or_none(self, chat_id: int, user_id: int): ...
    def create(self, user_id: int, title: str, pdf_name: str): ...
    def list_for_user(self, user_id: int) -> list: ...
    def delete(self, chat) -> None: ...
    def commit(self) -> None: ...
    def refresh(self, chat) -> None: ...


class ChunkRepository(Protocol):
    def save_many(self, chunks: list[DocumentChunk]) -> None: ...
    def delete_for_chat(self, chat_id: int) -> None: ...
    def get_for_chat(self, chat_id: int) -> list[DocumentChunk]: ...


class MessageRepository(Protocol):
    def add(self, chat_id: int, role: str, content: str) -> None: ...
    def get_recent(self, chat_id: int, limit: int) -> list[dict]: ...
    def get_all_for_chat(self, chat_id: int) -> list: ...


class UserRepository(Protocol):
    def get_by_google_sub(self, google_sub: str): ...
    def create(self, google_sub: str, email: str, name: str | None, picture_url: str | None): ...
    def update_profile(self, user, email: str, name: str | None, picture_url: str | None) -> None: ...
    def get_by_id(self, user_id: int): ...
